<a href="https://colab.research.google.com/github/mariea-aashif/Statistical-Learning-e22374/blob/main/assignment_5_introduction_to_numerical_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Foundations of Statistical Inference & Hypothesis Testing

This section checks the statistical foundation behind baseline monitoring. The main idea is to understand how sample estimates behave, why covariance estimation needs Bessel's correction, how hypothesis testing controls false alarms, and how first-moment homogeneity can be checked numerically using Wilks' Lambda.

## Part A: Theoretical Fundamentals  
### 1. Bias of the Maximum Likelihood Covariance Estimator

Let the observations be

$$
\mathbf{X}_1,\mathbf{X}_2,\ldots,\mathbf{X}_n \in \mathbb{R}^m
$$

with population mean

$$
\boldsymbol{\mu}=E[\mathbf{X}_i]
$$

and population covariance matrix

$$
\boldsymbol{\Sigma}=Var(\mathbf{X}_i).
$$

The sample mean is

$$
\widehat{\boldsymbol{\mu}}_n
=
\frac{1}{n}\sum_{i=1}^{n}\mathbf{X}_i.
$$

The raw maximum likelihood estimator of the covariance matrix is

$$
\widehat{\boldsymbol{\Sigma}}_{MLE}
=
\frac{1}{n}
\sum_{i=1}^{n}
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)^T.
$$

To examine its bias, use the identity

$$
\sum_{i=1}^{n}
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)^T
=
\sum_{i=1}^{n}
(\mathbf{X}_i-\boldsymbol{\mu})
(\mathbf{X}_i-\boldsymbol{\mu})^T
-
n(\widehat{\boldsymbol{\mu}}_n-\boldsymbol{\mu})
(\widehat{\boldsymbol{\mu}}_n-\boldsymbol{\mu})^T.
$$

Taking expectations,

$$
E\left[
\sum_{i=1}^{n}
(\mathbf{X}_i-\boldsymbol{\mu})
(\mathbf{X}_i-\boldsymbol{\mu})^T
\right]
=
n\boldsymbol{\Sigma}.
$$

Also,

$$
Var(\widehat{\boldsymbol{\mu}}_n)
=
\frac{1}{n}\boldsymbol{\Sigma}.
$$

Therefore,

$$
E\left[
n(\widehat{\boldsymbol{\mu}}_n-\boldsymbol{\mu})
(\widehat{\boldsymbol{\mu}}_n-\boldsymbol{\mu})^T
\right]
=
\boldsymbol{\Sigma}.
$$

So,

$$
E\left[
\sum_{i=1}^{n}
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)^T
\right]
=
(n-1)\boldsymbol{\Sigma}.
$$

Since the MLE divides by \(n\),

$$
E[\widehat{\boldsymbol{\Sigma}}_{MLE}]
=
\frac{1}{n}(n-1)\boldsymbol{\Sigma}
=
\frac{n-1}{n}\boldsymbol{\Sigma}.
$$

Therefore, the raw MLE covariance estimator is biased downward in finite samples.

To remove this bias, the scatter matrix is divided by \(n-1\) instead of \(n\):

$$
\mathbf{S}
=
\frac{1}{n-1}
\sum_{i=1}^{n}
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)
(\mathbf{X}_i-\widehat{\boldsymbol{\mu}}_n)^T.
$$

Then,

$$
E[\mathbf{S}]
=
\frac{1}{n-1}(n-1)\boldsymbol{\Sigma}
=
\boldsymbol{\Sigma}.
$$

Hence, Bessel's correction gives the unbiased empirical covariance estimator.

### 2. Type I Error, Type II Error, Power, and the Healthy Operation Ellipsoid

Under the null hypothesis \(H_0\), the structural asset is assumed to remain healthy. A test statistic is monitored to decide whether the system still behaves like the baseline condition or whether it has shifted away from it.

A Type I Error occurs when the system is actually healthy, but the test rejects \(H_0\). In structural health monitoring, this means the diagnostic system raises a false alarm even though the asset has not changed. The probability of this error is denoted by

$$
\alpha.
$$

A Type II Error occurs when the system is actually damaged or shifted, but the test fails to reject \(H_0\). In this case, the monitoring system misses a real abnormal condition. The probability of this error is

$$
\beta.
$$

The statistical power of the test is

$$
1-\beta.
$$

Power is the probability that the diagnostic layer correctly detects a real shift or damage condition.

If an engineer sets an extremely small significance threshold such as

$$
\alpha=0.0001,
$$

the test becomes very conservative. This reduces the probability of false alarms, but it also makes the rejection region much smaller. As a result, the system requires stronger evidence before declaring damage.

For a multivariate monitoring statistic, the healthy region can be represented by a confidence ellipsoid:

$$
(\mathbf{x}-\boldsymbol{\mu})^T
\boldsymbol{\Sigma}^{-1}
(\mathbf{x}-\boldsymbol{\mu})
\leq c_{\alpha}.
$$

When \(\alpha\) is made smaller, \(c_{\alpha}\) becomes larger. This expands the healthy operation confidence ellipsoid. More observations are then classified as healthy.

The consequence is that false alarms decrease, but the probability of missing smaller real shifts increases. Therefore, \(\beta\) increases and the power \(1-\beta\) decreases.

In practice, the plant becomes safer from unnecessary shutdowns, but less sensitive to early-stage damage.

### 2. Type I Error, Type II Error, Power, and the Healthy Operation Ellipsoid

Under the null hypothesis \(H_0\), the structural asset is assumed to remain healthy. A test statistic is monitored to decide whether the system still behaves like the baseline condition or whether it has shifted away from it.

A Type I Error occurs when the system is actually healthy, but the test rejects \(H_0\). In structural health monitoring, this means the diagnostic system raises a false alarm even though the asset has not changed. The probability of this error is denoted by

$$
\alpha.
$$

A Type II Error occurs when the system is actually damaged or shifted, but the test fails to reject \(H_0\). In this case, the monitoring system misses a real abnormal condition. The probability of this error is

$$
\beta.
$$

The statistical power of the test is

$$
1-\beta.
$$

Power is the probability that the diagnostic layer correctly detects a real shift or damage condition.

If an engineer sets an extremely small significance threshold such as

$$
\alpha=0.0001,
$$

the test becomes very conservative. This reduces the probability of false alarms, but it also makes the rejection region much smaller. As a result, the system requires stronger evidence before declaring damage.

For a multivariate monitoring statistic, the healthy region can be represented by a confidence ellipsoid:

$$
(\mathbf{x}-\boldsymbol{\mu})^T
\boldsymbol{\Sigma}^{-1}
(\mathbf{x}-\boldsymbol{\mu})
\leq c_{\alpha}.
$$

When \(\alpha\) is made smaller, \(c_{\alpha}\) becomes larger. This expands the healthy operation confidence ellipsoid. More observations are then classified as healthy.

The consequence is that false alarms decrease, but the probability of missing smaller real shifts increases. Therefore, \(\beta\) increases and the power \(1-\beta\) decreases.

In practice, the plant becomes safer from unnecessary shutdowns, but less sensitive to early-stage damage.

## Part C: Numerical Verification

The first numerical task checks whether the joint mean vector remains constant over time. The dataset is divided into five consecutive blocks of 1000 observations each. A MANOVA-style test is then applied using Wilks' Lambda.

The null hypothesis is:

$$
H_0: \text{the joint mean vector is constant across all time blocks.}
$$

The alternative hypothesis is:

$$
H_1: \text{at least one time block has a shifted joint mean vector.}
$$

The test statistic is based on

$$
\Lambda = \frac{|\mathbf{W}|}{|\mathbf{B}+\mathbf{W}|},
$$

where $\mathbf{W}$ is the within-block scatter matrix and $\mathbf{B}$ is the between-block scatter matrix.

Bartlett's chi-square approximation is

$$
\chi^2_{calc}
=
-\left(n-1-\frac{m+g}{2}\right)\ln(\Lambda).
$$

The degrees of freedom are

$$
df=m(g-1).
$$

In [29]:
# ============================================================
# Foundations of Statistical Inference & Hypothesis Testing
# Part C: Numerical Verification
# MANOVA first-moment homogeneity test using Wilks' Lambda
# ============================================================

import numpy as np
import pandas as pd
import scipy.stats as stats

from IPython.display import Markdown, display

# --- DO NOT MODIFY: Synthetic Strain Sensor Data Generator ---
np.random.seed(42)

n_samples = 5000
n_features = 3

base_data = np.random.multivariate_normal(
    mean=[0.5, -0.2, 1.1],
    cov=[
        [0.09, 0.02, 0.01],
        [0.02, 0.06, 0.03],
        [0.01, 0.03, 0.05]
    ],
    size=n_samples
)

# Injecting a subtle, hidden structural drift in the final 1,000 snapshots
base_data[4000:, 0] += 0.015  # Sensor 1 drift
base_data[4000:, 2] -= 0.010  # Sensor 3 drift

df_strain = pd.DataFrame(
    base_data,
    columns=["Strain_Ch1", "Strain_Ch2", "Strain_Ch3"]
)


def verify_first_moment_homogeneity(df: pd.DataFrame, g_chunks: int = 5, alpha: float = 0.05):
    """
    Partitions the dataset into g consecutive non-overlapping chunks and evaluates
    first-moment homogeneity using Wilks' Lambda and Bartlett's Chi-Square approximation.
    """

    X = df.select_dtypes(include=[np.number]).to_numpy(dtype=float)
    n, m = X.shape

    if n % g_chunks != 0:
        raise ValueError("The number of samples must be divisible by g_chunks.")

    chunk_size = n // g_chunks

    blocks = [
        X[i * chunk_size:(i + 1) * chunk_size, :]
        for i in range(g_chunks)
    ]

    global_mean = np.mean(X, axis=0)

    W = np.zeros((m, m))
    B = np.zeros((m, m))

    chunk_means = []

    for block in blocks:
        chunk_mean = np.mean(block, axis=0)
        chunk_means.append(chunk_mean)

        centered_block = block - chunk_mean
        W += centered_block.T @ centered_block

        mean_difference = (chunk_mean - global_mean).reshape(-1, 1)
        B += block.shape[0] * (mean_difference @ mean_difference.T)

    T = B + W

    sign_W, logdet_W = np.linalg.slogdet(W)
    sign_T, logdet_T = np.linalg.slogdet(T)

    wilks_lambda = np.exp(logdet_W - logdet_T)

    chi_square_calc = -(n - 1 - ((m + g_chunks) / 2)) * np.log(wilks_lambda)

    df_chi_square = m * (g_chunks - 1)

    p_value = stats.chi2.sf(chi_square_calc, df=df_chi_square)

    if p_value < alpha:
        conclusion = "Reject H0: the baseline center has shifted over time."
    else:
        conclusion = "Fail to reject H0: the first moment is homogeneous."

    results = {
        "n_samples": n,
        "n_features": m,
        "g_chunks": g_chunks,
        "chunk_size": chunk_size,
        "Wilks_Lambda": wilks_lambda,
        "Bartlett_Chi_Square": chi_square_calc,
        "Degrees_of_Freedom": df_chi_square,
        "p_value": p_value,
        "alpha": alpha,
        "Conclusion": conclusion
    }

    chunk_means_df = pd.DataFrame(
        chunk_means,
        columns=df.select_dtypes(include=[np.number]).columns,
        index=[f"Chunk_{i+1}" for i in range(g_chunks)]
    )

    return results, chunk_means_df


results_moments, chunk_means = verify_first_moment_homogeneity(df_strain, g_chunks=5)

print("=== MANOVA First Moment Homogeneity Test ===")
for key, value in results_moments.items():
    print(f"{key}: {value}")

print("\n=== Chunk Means ===")
display(chunk_means)

=== MANOVA First Moment Homogeneity Test ===
n_samples: 5000
n_features: 3
g_chunks: 5
chunk_size: 1000
Wilks_Lambda: 0.9904519796929591
Bartlett_Chi_Square: 47.9215049961488
Degrees_of_Freedom: 12
p_value: 3.225525950915837e-06
alpha: 0.05
Conclusion: Reject H0: the baseline center has shifted over time.

=== Chunk Means ===

         Strain_Ch1  Strain_Ch2  Strain_Ch3
Chunk_1    0.486070   -0.213878    1.099031
Chunk_2    0.509420   -0.180987    1.119021
Chunk_3    0.502061   -0.199215    1.109538
Chunk_4    0.508964   -0.191861    1.095333
Chunk_5    0.514261   -0.217772    1.064828

### Numerical Interpretation

The dataset was divided into five consecutive non-overlapping chunks, each containing 1000 observations. The purpose of the test was to check whether the joint mean vector stayed constant across time.

Wilks' Lambda measures how much of the total scatter remains within the groups after accounting for the separation between group means. A value of $\Lambda$ close to 1 suggests that the group means are similar. A smaller value suggests that the group means are more separated.

Using Bartlett's chi-square approximation, the calculated test statistic is compared with a chi-square distribution with

$$
df=m(g-1)=3(5-1)=12.
$$

The computed p-value is smaller than

$$
\alpha = 0.05.
$$

Therefore, the null hypothesis is rejected.

This means that the first moment is not homogeneous across the time blocks. The baseline center has shifted over time. In the context of structural health monitoring, this indicates that the baseline data cannot be treated as perfectly stationary in its joint mean.

# Geometric Subspace Optimization via Principal Component Analysis

This section studies how PCA transforms correlated sensor data into a new orthogonal coordinate system. The main purpose is to show how covariance becomes diagonal in principal component space, how total variance is preserved, and how the $T^2$ and $Q$ statistics behave when the retained subspace size $k$ changes.

## Part A: Theoretical Fundamentals  
### 1. Coordinate Projection and Diagonal Covariance

Let the centered observation vector be

$$
\widetilde{\mathbf{X}}_i=\mathbf{X}_i-\boldsymbol{\mu}.
$$

Since the vector is centered,

$$
E[\widetilde{\mathbf{X}}_i]=\mathbf{0}.
$$

The covariance matrix is

$$
\boldsymbol{\Sigma}
=
E[\widetilde{\mathbf{X}}_i\widetilde{\mathbf{X}}_i^T].
$$

Because $\boldsymbol{\Sigma}$ is symmetric and positive semidefinite, it admits the spectral decomposition

$$
\boldsymbol{\Sigma}
=
\mathbf{P}\boldsymbol{\Lambda}\mathbf{P}^T,
$$

where $\mathbf{P}$ is an orthogonal matrix containing the eigenvectors and $\boldsymbol{\Lambda}$ is a diagonal matrix containing the eigenvalues.

The PCA-transformed vector is

$$
\mathbf{Z}_i
=
\mathbf{P}^T\widetilde{\mathbf{X}}_i.
$$

The covariance of the transformed vector is

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T].
$$

Substituting the PCA transformation,

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
E[(\mathbf{P}^T\widetilde{\mathbf{X}}_i)
(\mathbf{P}^T\widetilde{\mathbf{X}}_i)^T].
$$

Since

$$
(\mathbf{P}^T\widetilde{\mathbf{X}}_i)^T
=
\widetilde{\mathbf{X}}_i^T\mathbf{P},
$$

it follows that

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
E[\mathbf{P}^T\widetilde{\mathbf{X}}_i
\widetilde{\mathbf{X}}_i^T\mathbf{P}].
$$

The matrix $\mathbf{P}$ is deterministic, so it can be taken outside the expectation:

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
\mathbf{P}^T
E[\widetilde{\mathbf{X}}_i\widetilde{\mathbf{X}}_i^T]
\mathbf{P}.
$$

Since

$$
E[\widetilde{\mathbf{X}}_i\widetilde{\mathbf{X}}_i^T]
=
\boldsymbol{\Sigma},
$$

we get

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
\mathbf{P}^T\boldsymbol{\Sigma}\mathbf{P}.
$$

Using the spectral decomposition,

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
\mathbf{P}^T
(\mathbf{P}\boldsymbol{\Lambda}\mathbf{P}^T)
\mathbf{P}.
$$

Since $\mathbf{P}^T\mathbf{P}=\mathbf{I}$,

$$
E[\mathbf{Z}_i\mathbf{Z}_i^T]
=
\boldsymbol{\Lambda}.
$$

Thus, the covariance matrix in principal component space is diagonal.

This diagonal result means that the transformed coordinates are uncorrelated. For two different coordinates $Z_{i,j}$ and $Z_{i,k}$, where $j\neq k$,

$$
Cov(Z_{i,j},Z_{i,k})=0.
$$

Geometrically, PCA rotates the original coordinate system so that the new axes align with the main directions of variation. Statistically, each principal component captures variance independently from the others.

### 2. Total Variance Conservation and Variance Ratios

The total variance in the raw coordinate system is measured using the trace of the covariance matrix:

$$
tr(\boldsymbol{\Sigma}).
$$

Using the spectral decomposition,

$$
\boldsymbol{\Sigma}
=
\mathbf{P}\boldsymbol{\Lambda}\mathbf{P}^T.
$$

Therefore,

$$
tr(\boldsymbol{\Sigma})
=
tr(\mathbf{P}\boldsymbol{\Lambda}\mathbf{P}^T).
$$

Using the cyclic property of the trace,

$$
tr(\mathbf{P}\boldsymbol{\Lambda}\mathbf{P}^T)
=
tr(\boldsymbol{\Lambda}\mathbf{P}^T\mathbf{P}).
$$

Since $\mathbf{P}^T\mathbf{P}=\mathbf{I}$,

$$
tr(\boldsymbol{\Sigma})
=
tr(\boldsymbol{\Lambda}).
$$

Because $\boldsymbol{\Lambda}$ is diagonal,

$$
tr(\boldsymbol{\Lambda})
=
\sum_{j=1}^{m}\lambda_j.
$$

Hence,

$$
tr(\boldsymbol{\Sigma})
=
tr(\boldsymbol{\Lambda})
=
\sum_{j=1}^{m}\lambda_j.
$$

This proves that PCA does not destroy variance. It only redistributes the same total variance across orthogonal principal directions.

If the first $k$ principal components are retained, the cumulative explained variance ratio is

$$
\Phi(k)
=
\frac{\sum_{j=1}^{k}\widehat{\lambda}_j}
{\sum_{j=1}^{m}\widehat{\lambda}_j}.
$$

The residual unexplained variance ratio is

$$
\Psi(k)
=
\frac{\sum_{j=k+1}^{m}\widehat{\lambda}_j}
{\sum_{j=1}^{m}\widehat{\lambda}_j}.
$$

Since all variance is either retained or residual,

$$
\Phi(k)+\Psi(k)=1.
$$

### 3. Reconstruction, Residual Error, \(T^2\), and \(Q\)

For a centered observation,

$$
\mathbf{x}_i-\widehat{\boldsymbol{\mu}}_n,
$$

the PCA coordinate representation can be partitioned into retained and residual parts:

$$
\mathbf{x}_i-\widehat{\boldsymbol{\mu}}_n
=
\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}
+
\widehat{\mathbf{P}}_{m-k}\mathbf{z}_{i,m-k}.
$$

The reconstructed vector using only the first $k$ principal components is

$$
\widehat{\mathbf{x}}_i
=
\widehat{\boldsymbol{\mu}}_n
+
\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}.
$$

The residual error vector is

$$
\mathbf{e}_i
=
\mathbf{x}_i-\widehat{\mathbf{x}}_i.
$$

Substituting the reconstructed vector,

$$
\mathbf{e}_i
=
\mathbf{x}_i
-
\left(
\widehat{\boldsymbol{\mu}}_n
+
\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}
\right).
$$

Therefore,

$$
\mathbf{e}_i
=
(\mathbf{x}_i-\widehat{\boldsymbol{\mu}}_n)
-
\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}.
$$

Using the PCA partition,

$$
\mathbf{e}_i
=
\widehat{\mathbf{P}}_{m-k}\mathbf{z}_{i,m-k}.
$$

Since the retained and residual PCA subspaces are orthogonal, the Pythagorean identity gives

$$
\|\mathbf{x}_i-\widehat{\boldsymbol{\mu}}_n\|^2
=
\|\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}\|^2
+
\|\widehat{\mathbf{P}}_{m-k}\mathbf{z}_{i,m-k}\|^2.
$$

Because PCA loading matrices are orthonormal,

$$
\|\widehat{\mathbf{P}}_k\mathbf{z}_{i,k}\|^2
=
\|\mathbf{z}_{i,k}\|^2
$$

and

$$
\|\widehat{\mathbf{P}}_{m-k}\mathbf{z}_{i,m-k}\|^2
=
\|\mathbf{z}_{i,m-k}\|^2.
$$

Thus,

$$
\|\mathbf{x}_i-\widehat{\boldsymbol{\mu}}_n\|^2
=
\|\mathbf{z}_{i,k}\|^2
+
\|\mathbf{z}_{i,m-k}\|^2.
$$

Hotelling's $T^2$ statistic measures abnormal movement inside the retained principal component subspace:

$$
T_i^2
=
\sum_{j=1}^{k}
\frac{z_{i,j}^2}{\widehat{\lambda}_j}.
$$

The $Q$ statistic, also called SPE, measures the residual energy outside the retained PCA subspace:

$$
Q_i
=
\sum_{j=k+1}^{m}z_{i,j}^2.
$$

An environmental load anomaly such as extreme wind is usually captured by $T^2$, because it changes the magnitude of variation inside the normal operating subspace. An internal structural fracture is often more visible in $Q$, because it can create a new pattern that does not lie in the learned baseline subspace.

## Part B: Numerical Verification

The numerical verification checks how the mean Hotelling's $T^2$ statistic and the mean $Q$ statistic change as the retained PCA subspace size increases.

For each value

$$
k \in \{1,2,3\},
$$

the retained principal component scores are used to calculate

$$
T_i^2
=
\sum_{j=1}^{k}
\frac{z_{i,j}^2}{\widehat{\lambda}_j},
$$

and the discarded scores are used to calculate

$$
Q_i
=
\sum_{j=k+1}^{m}z_{i,j}^2.
$$

If PCA is working as expected, increasing $k$ should increase the retained energy measured by $T^2$, while reducing the residual energy measured by $Q$.

In [30]:
# ============================================================
# Geometric Subspace Optimization via PCA
# Part B: Numerical Verification
# Hotelling's T² and Q statistic for k = 1, 2, 3
# ============================================================

import numpy as np
import pandas as pd
from IPython.display import Markdown, display

class PCADiagnosticOptimizer:
    def __init__(self):
        self.mean_ = None
        self.std_ = None
        self.covariance_matrix_ = None
        self.eigenvalues_ = None
        self.eigenvectors_ = None
        self.scores_ = None

    def fit_analyze(self, df: pd.DataFrame):
        X = df.select_dtypes(include=[np.number]).to_numpy(dtype=float)

        n, m = X.shape

        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0, ddof=1)
        self.std_ = np.where(self.std_ < 1e-15, 1e-15, self.std_)

        Z_standardized = (X - self.mean_) / self.std_

        self.covariance_matrix_ = np.cov(Z_standardized, rowvar=False, ddof=1)

        eigenvalues, eigenvectors = np.linalg.eigh(self.covariance_matrix_)

        sorted_indices = np.argsort(eigenvalues)[::-1]

        self.eigenvalues_ = eigenvalues[sorted_indices]
        self.eigenvectors_ = eigenvectors[:, sorted_indices]

        self.scores_ = Z_standardized @ self.eigenvectors_

        max_k = min(3, m - 1)

        results = []

        for k in range(1, max_k + 1):
            T2_values = np.sum(
                (self.scores_[:, :k] ** 2) / self.eigenvalues_[:k],
                axis=1
            )

            Q_values = np.sum(
                self.scores_[:, k:] ** 2,
                axis=1
            )

            results.append({
                "k": k,
                "Mean_T2": np.mean(T2_values),
                "Mean_Q": np.mean(Q_values),
                "Captured_Variance_Ratio": np.sum(self.eigenvalues_[:k]) / np.sum(self.eigenvalues_),
                "Residual_Variance_Ratio": np.sum(self.eigenvalues_[k:]) / np.sum(self.eigenvalues_)
            })

        results_df = pd.DataFrame(results)

        return results_df


np.random.seed(42)

n_samples = 3000

df_pca_baseline = pd.DataFrame(
    np.random.multivariate_normal(
        mean=[0, 0, 0, 0],
        cov=[
            [1.00, 0.75, 0.45, 0.20],
            [0.75, 1.00, 0.50, 0.25],
            [0.45, 0.50, 1.00, 0.60],
            [0.20, 0.25, 0.60, 1.00]
        ],
        size=n_samples
    ),
    columns=["Sensor_1", "Sensor_2", "Sensor_3", "Sensor_4"]
)

pca_optimizer = PCADiagnosticOptimizer()
pca_verification_results = pca_optimizer.fit_analyze(df_pca_baseline)

print("=== PCA Eigenvalues ===")
for i, value in enumerate(pca_optimizer.eigenvalues_, start=1):
    print(f"lambda_{i}: {value}")

print("\n=== PCA Hotelling's T² and Q Verification ===")
display(pca_verification_results)

=== PCA Eigenvalues ===
lambda_1: 2.4026114753803265
lambda_2: 1.0067026976567222
lambda_3: 0.3429083692231631
lambda_4: 0.2477774577397886

=== PCA Hotelling's T² and Q Verification ===

   k   Mean_T2    Mean_Q  Captured_Variance_Ratio  Residual_Variance_Ratio
0  1  0.999667  1.596856                 0.600653                 0.399347
1  2  1.999333  0.590489                 0.852329                 0.147671
2  3  2.999000  0.247695                 0.938056                 0.061944

### Numerical Interpretation

The standardized sensor data was projected into the principal component coordinate system using the eigenvectors of the unbiased sample covariance matrix.

For each retained subspace size $k$, the mean $T^2$ statistic and the mean $Q$ statistic were calculated.

The results show the expected behaviour. As $k$ increases, more principal components are included in the retained model space. Therefore, the mean $T^2$ statistic increases because more normalized principal component energy is being tracked inside the model.

At the same time, the mean $Q$ statistic decreases because fewer components are left in the residual space. This confirms the theoretical PCA energy split between the retained subspace and the residual subspace.

The captured variance ratio also increases with $k$, while the residual variance ratio decreases. This supports the idea that PCA progressively moves variance from the unexplained residual space into the explained principal component space.

# Latent Subspace Decomposition via Factor Analysis

This section studies Factor Analysis as a generative method. Unlike PCA, which focuses on total variance, Factor Analysis separates the variation in each sensor into shared structural variation and sensor-specific noise.

This is useful in diagnostics because a noisy sensor should not be confused with a real structural mode.

## Part A: Theoretical Fundamentals  
### 1. Fundamental Equation of Factor Analysis

Let the standardized zero-mean sensor vector be

$$
\mathbf{Z}_i \in \mathbb{R}^m.
$$

The population correlation matrix is

$$
\mathbf{R}
=
E[\mathbf{Z}_i\mathbf{Z}_i^T].
$$

The Factor Analysis model is

$$
\mathbf{Z}_i
=
\boldsymbol{\Lambda}\mathbf{F}_i
+
\boldsymbol{\epsilon}_i,
$$

where $\boldsymbol{\Lambda}$ is the factor loading matrix, $\mathbf{F}_i$ is the vector of common latent factors, and $\boldsymbol{\epsilon}_i$ is the sensor-specific error vector.

The model assumptions are

$$
E[\mathbf{F}_i]=\mathbf{0},
$$

$$
E[\mathbf{F}_i\mathbf{F}_i^T]=\mathbf{I},
$$

$$
E[\boldsymbol{\epsilon}_i]=\mathbf{0},
$$

and

$$
E[\boldsymbol{\epsilon}_i\boldsymbol{\epsilon}_i^T]
=
\boldsymbol{\Psi}.
$$

Here,

$$
\boldsymbol{\Psi}
=
diag(\varphi_1^2,\varphi_2^2,\ldots,\varphi_m^2).
$$

The factors and errors are independent, so

$$
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T]=\mathbf{0}.
$$

Starting from the model,

$$
\mathbf{Z}_i
=
\boldsymbol{\Lambda}\mathbf{F}_i
+
\boldsymbol{\epsilon}_i.
$$

The correlation matrix is

$$
\mathbf{R}
=
E[\mathbf{Z}_i\mathbf{Z}_i^T].
$$

Substituting the model,

$$
\mathbf{R}
=
E[
(\boldsymbol{\Lambda}\mathbf{F}_i+\boldsymbol{\epsilon}_i)
(\boldsymbol{\Lambda}\mathbf{F}_i+\boldsymbol{\epsilon}_i)^T
].
$$

Expanding,

$$
\mathbf{R}
=
E[
\boldsymbol{\Lambda}\mathbf{F}_i\mathbf{F}_i^T\boldsymbol{\Lambda}^T
+
\boldsymbol{\Lambda}\mathbf{F}_i\boldsymbol{\epsilon}_i^T
+
\boldsymbol{\epsilon}_i\mathbf{F}_i^T\boldsymbol{\Lambda}^T
+
\boldsymbol{\epsilon}_i\boldsymbol{\epsilon}_i^T
].
$$

Taking expectations term by term,

$$
\mathbf{R}
=
\boldsymbol{\Lambda}E[\mathbf{F}_i\mathbf{F}_i^T]\boldsymbol{\Lambda}^T
+
\boldsymbol{\Lambda}E[\mathbf{F}_i\boldsymbol{\epsilon}_i^T]
+
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T]\boldsymbol{\Lambda}^T
+
E[\boldsymbol{\epsilon}_i\boldsymbol{\epsilon}_i^T].
$$

Using the assumptions, the two cross terms become zero. Therefore,

$$
\mathbf{R}
=
\boldsymbol{\Lambda}\mathbf{I}\boldsymbol{\Lambda}^T
+
\boldsymbol{\Psi}.
$$

So,

$$
\mathbf{R}
=
\boldsymbol{\Lambda}\boldsymbol{\Lambda}^T
+
\boldsymbol{\Psi}.
$$

This is the fundamental equation of Factor Analysis.

For the $j$-th sensor, the diagonal entry is

$$
R_{jj}
=
h_j^2+\varphi_j^2.
$$

Since the data is standardized,

$$
R_{jj}=1.
$$

The communality is

$$
h_j^2
=
\sum_{r=1}^{k}\lambda_{jr}^2.
$$

It measures the part of sensor $j$'s variance explained by the shared latent factors.

The uniqueness is

$$
\varphi_j^2
=
1-h_j^2.
$$

It measures the part of sensor $j$'s variance that remains sensor-specific. In asset diagnostics, high communality means the sensor follows the shared structural behaviour. High uniqueness means the sensor contains isolated noise or local sensor-specific behaviour.

### 2. PCA Loadings and Varimax-Rotated Factor Loadings

A PCA loading vector is obtained from the eigenvectors of the covariance or correlation matrix. Its main purpose is to capture maximum total variance. The first principal component captures the largest possible variance, the second captures the largest remaining orthogonal variance, and so on.

Because of this, PCA loadings are arranged according to the variance hierarchy

$$
\lambda_1 \geq \lambda_2 \geq \cdots \geq \lambda_m.
$$

This makes PCA strong for compression, but not always easy to interpret physically. A single principal component can mix several sensor behaviours together.

A Varimax-rotated factor loading vector has a different purpose. It is rotated to improve interpretability. The rotation tries to make each sensor load strongly on a smaller number of factors and weakly on the others. This gives a cleaner factor structure.

If $\mathbf{T}$ is an orthogonal rotation matrix, then the rotated loading matrix is

$$
\boldsymbol{\Lambda}_{rot}
=
\boldsymbol{\Lambda}\mathbf{T}.
$$

Since the rotation is orthogonal,

$$
\mathbf{T}\mathbf{T}^T=\mathbf{I}.
$$

The covariance reproduced by the common factors is

$$
\boldsymbol{\Lambda}_{rot}
\boldsymbol{\Lambda}_{rot}^T.
$$

Substituting the rotated loading matrix,

$$
\boldsymbol{\Lambda}_{rot}
\boldsymbol{\Lambda}_{rot}^T
=
(\boldsymbol{\Lambda}\mathbf{T})
(\boldsymbol{\Lambda}\mathbf{T})^T.
$$

This becomes

$$
\boldsymbol{\Lambda}_{rot}
\boldsymbol{\Lambda}_{rot}^T
=
\boldsymbol{\Lambda}\mathbf{T}\mathbf{T}^T\boldsymbol{\Lambda}^T.
$$

Since

$$
\mathbf{T}\mathbf{T}^T=\mathbf{I},
$$

we get

$$
\boldsymbol{\Lambda}_{rot}
\boldsymbol{\Lambda}_{rot}^T
=
\boldsymbol{\Lambda}\boldsymbol{\Lambda}^T.
$$

Therefore, orthogonal rotation changes the appearance of the factor loading columns, but it does not change the global covariance approximation.

The communality of sensor $j$ is the row-wise sum of squared loadings:

$$
h_j^2
=
\sum_{r=1}^{k}\lambda_{jr}^2.
$$

Because orthogonal rotation preserves row lengths, the communality of each sensor remains unchanged. This is why Varimax can improve interpretation without changing how much shared variance each sensor has.

### 3. Thomson's Regression Factor Score Estimator

The common factors $\mathbf{F}_i$ are latent, so they cannot be directly observed. Unlike PCA scores, factor scores are not obtained by a direct geometric projection. Instead, they are estimated using conditional expectation.

Define the joint vector

$$
\mathbf{Y}_i
=
\begin{bmatrix}
\mathbf{Z}_i \\
\mathbf{F}_i
\end{bmatrix}.
$$

The joint covariance matrix is

$$
\boldsymbol{\Sigma}_{YY}
=
\begin{bmatrix}
Var(\mathbf{Z}_i) & Cov(\mathbf{Z}_i,\mathbf{F}_i) \\
Cov(\mathbf{F}_i,\mathbf{Z}_i) & Var(\mathbf{F}_i)
\end{bmatrix}.
$$

From the factor model,

$$
\mathbf{Z}_i
=
\boldsymbol{\Lambda}\mathbf{F}_i
+
\boldsymbol{\epsilon}_i.
$$

The covariance of $\mathbf{Z}_i$ is

$$
Var(\mathbf{Z}_i)=\mathbf{R}.
$$

The covariance of $\mathbf{F}_i$ is

$$
Var(\mathbf{F}_i)=\mathbf{I}.
$$

Now,

$$
Cov(\mathbf{Z}_i,\mathbf{F}_i)
=
E[\mathbf{Z}_i\mathbf{F}_i^T].
$$

Substituting the factor model,

$$
E[\mathbf{Z}_i\mathbf{F}_i^T]
=
E[
(\boldsymbol{\Lambda}\mathbf{F}_i+\boldsymbol{\epsilon}_i)
\mathbf{F}_i^T
].
$$

So,

$$
E[\mathbf{Z}_i\mathbf{F}_i^T]
=
\boldsymbol{\Lambda}E[\mathbf{F}_i\mathbf{F}_i^T]
+
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T].
$$

Using

$$
E[\mathbf{F}_i\mathbf{F}_i^T]=\mathbf{I}
$$

and

$$
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T]=\mathbf{0},
$$

we get

$$
Cov(\mathbf{Z}_i,\mathbf{F}_i)=\boldsymbol{\Lambda}.
$$

Therefore,

$$
Cov(\mathbf{F}_i,\mathbf{Z}_i)=\boldsymbol{\Lambda}^T.
$$

Hence,

$$
\boldsymbol{\Sigma}_{YY}
=
\begin{bmatrix}
\mathbf{R} & \boldsymbol{\Lambda} \\
\boldsymbol{\Lambda}^T & \mathbf{I}
\end{bmatrix}.
$$

For a partitioned multivariate normal system,

$$
E[\mathbf{X}_2|\mathbf{x}_1]
=
\boldsymbol{\mu}_2
+
\boldsymbol{\Sigma}_{21}
\boldsymbol{\Sigma}_{11}^{-1}
(\mathbf{x}_1-\boldsymbol{\mu}_1).
$$

Here,

$$
\mathbf{X}_1=\mathbf{Z}_i,
$$

and

$$
\mathbf{X}_2=\mathbf{F}_i.
$$

The standardized means are zero, so

$$
\boldsymbol{\mu}_1=\mathbf{0},
\qquad
\boldsymbol{\mu}_2=\mathbf{0}.
$$

Also,

$$
\boldsymbol{\Sigma}_{21}=\boldsymbol{\Lambda}^T,
$$

and

$$
\boldsymbol{\Sigma}_{11}=\mathbf{R}.
$$

Therefore,

$$
E[\mathbf{F}_i|\mathbf{z}_i]
=
\boldsymbol{\Lambda}^T\mathbf{R}^{-1}\mathbf{z}_i.
$$

Thus, Thomson's regression factor score estimator is

$$
\mathbf{f}_i
=
\boldsymbol{\Lambda}^T\mathbf{R}^{-1}\mathbf{z}_i.
$$

### 3. Thomson's Regression Factor Score Estimator

The common factors $\mathbf{F}_i$ are latent, so they cannot be directly observed. Unlike PCA scores, factor scores are not obtained by a direct geometric projection. Instead, they are estimated using conditional expectation.

Define the joint vector

$$
\mathbf{Y}_i
=
\begin{bmatrix}
\mathbf{Z}_i \\
\mathbf{F}_i
\end{bmatrix}.
$$

The joint covariance matrix is

$$
\boldsymbol{\Sigma}_{YY}
=
\begin{bmatrix}
Var(\mathbf{Z}_i) & Cov(\mathbf{Z}_i,\mathbf{F}_i) \\
Cov(\mathbf{F}_i,\mathbf{Z}_i) & Var(\mathbf{F}_i)
\end{bmatrix}.
$$

From the factor model,

$$
\mathbf{Z}_i
=
\boldsymbol{\Lambda}\mathbf{F}_i
+
\boldsymbol{\epsilon}_i.
$$

The covariance of $\mathbf{Z}_i$ is

$$
Var(\mathbf{Z}_i)=\mathbf{R}.
$$

The covariance of $\mathbf{F}_i$ is

$$
Var(\mathbf{F}_i)=\mathbf{I}.
$$

Now,

$$
Cov(\mathbf{Z}_i,\mathbf{F}_i)
=
E[\mathbf{Z}_i\mathbf{F}_i^T].
$$

Substituting the factor model,

$$
E[\mathbf{Z}_i\mathbf{F}_i^T]
=
E[
(\boldsymbol{\Lambda}\mathbf{F}_i+\boldsymbol{\epsilon}_i)
\mathbf{F}_i^T
].
$$

So,

$$
E[\mathbf{Z}_i\mathbf{F}_i^T]
=
\boldsymbol{\Lambda}E[\mathbf{F}_i\mathbf{F}_i^T]
+
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T].
$$

Using

$$
E[\mathbf{F}_i\mathbf{F}_i^T]=\mathbf{I}
$$

and

$$
E[\boldsymbol{\epsilon}_i\mathbf{F}_i^T]=\mathbf{0},
$$

we get

$$
Cov(\mathbf{Z}_i,\mathbf{F}_i)=\boldsymbol{\Lambda}.
$$

Therefore,

$$
Cov(\mathbf{F}_i,\mathbf{Z}_i)=\boldsymbol{\Lambda}^T.
$$

Hence,

$$
\boldsymbol{\Sigma}_{YY}
=
\begin{bmatrix}
\mathbf{R} & \boldsymbol{\Lambda} \\
\boldsymbol{\Lambda}^T & \mathbf{I}
\end{bmatrix}.
$$

For a partitioned multivariate normal system,

$$
E[\mathbf{X}_2|\mathbf{x}_1]
=
\boldsymbol{\mu}_2
+
\boldsymbol{\Sigma}_{21}
\boldsymbol{\Sigma}_{11}^{-1}
(\mathbf{x}_1-\boldsymbol{\mu}_1).
$$

Here,

$$
\mathbf{X}_1=\mathbf{Z}_i,
$$

and

$$
\mathbf{X}_2=\mathbf{F}_i.
$$

The standardized means are zero, so

$$
\boldsymbol{\mu}_1=\mathbf{0},
\qquad
\boldsymbol{\mu}_2=\mathbf{0}.
$$

Also,

$$
\boldsymbol{\Sigma}_{21}=\boldsymbol{\Lambda}^T,
$$

and

$$
\boldsymbol{\Sigma}_{11}=\mathbf{R}.
$$

Therefore,

$$
E[\mathbf{F}_i|\mathbf{z}_i]
=
\boldsymbol{\Lambda}^T\mathbf{R}^{-1}\mathbf{z}_i.
$$

Thus, Thomson's regression factor score estimator is

$$
\mathbf{f}_i
=
\boldsymbol{\Lambda}^T\mathbf{R}^{-1}\mathbf{z}_i.
$$

## Part B: Parametric Factor Partition Engine and UI Architecture

The numerical Factor Analysis engine standardizes the sensor data, checks dimensionality conditions, fits a latent factor model, applies Varimax rotation, and separates each sensor into communality and uniqueness.

The hidden factor scores are estimated using Thomson's regression method:

$$
F
=
ZR^{-1}\Lambda_{rotated}.
$$

The dashboard then displays four diagnostic views: the rotated loading heatmap, the communality-uniqueness partition, the sensor uniqueness profile, and the empirical variance of the factor scores.

In [31]:
# ============================================================
# Latent Subspace Decomposition via Factor Analysis
# Part B: Parametric Factor Partition Engine & UI Architecture
# ============================================================

import numpy as np
import pandas as pd

from sklearn.decomposition import FactorAnalysis
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from IPython.display import Markdown, display


# ------------------------------------------------------------
# Synthetic multi-sensor asset data
# ------------------------------------------------------------

np.random.seed(42)

n_samples = 2500

f1 = np.random.normal(0, 1, n_samples)  # Primary structural mode/load
f2 = np.random.normal(0, 1, n_samples)  # Secondary operational mode

s1 = 0.85 * f1 + 0.10 * f2 + np.random.normal(0, 0.30, n_samples)
s2 = 0.80 * f1 + 0.15 * f2 + np.random.normal(0, 0.35, n_samples)
s3 = 0.12 * f1 + 0.90 * f2 + np.random.normal(0, 0.25, n_samples)
s4 = 0.02 * f1 + 0.05 * f2 + np.random.normal(0, 1.40, n_samples)

df_asset = pd.DataFrame(
    data=np.vstack([s1, s2, s3, s4]).T,
    columns=["Sensor_1", "Sensor_2", "Sensor_3", "Sensor_4"]
)

display(df_asset.head())


# ------------------------------------------------------------
# Varimax rotation
# ------------------------------------------------------------

def varimax(Phi, gamma=1.0, q=50, tol=1e-6):
    """
    Performs orthogonal Varimax rotation on a loading matrix.
    """

    p, k = Phi.shape
    R = np.eye(k)
    d_old = 0

    for _ in range(q):
        Lambda = Phi @ R

        u, s, vh = np.linalg.svd(
            Phi.T @ (
                Lambda**3
                - (gamma / p) * Lambda @ np.diag(np.diag(Lambda.T @ Lambda))
            )
        )

        R = u @ vh
        d_new = np.sum(s)

        if d_old != 0 and d_new / d_old < 1 + tol:
            break

        d_old = d_new

    return Phi @ R, R


# ------------------------------------------------------------
# Factor Analysis diagnostic engine
# ------------------------------------------------------------

class FactorAnalysisDiagnosticEngine:
    def __init__(self, n_factors=2):
        self.n_factors = n_factors
        self.numeric_columns_ = None
        self.mean_ = None
        self.std_ = None
        self.Z_ = None
        self.R_ = None
        self.loadings_raw_ = None
        self.loadings_rotated_ = None
        self.rotation_matrix_ = None
        self.communality_ = None
        self.uniqueness_ = None
        self.factor_scores_ = None
        self.factor_score_variance_ = None

    def fit(self, df: pd.DataFrame):
        numeric_df = df.select_dtypes(include=[np.number]).copy()
        self.numeric_columns_ = numeric_df.columns.tolist()

        X = numeric_df.to_numpy(dtype=float)
        n, m = X.shape

        if n <= m:
            raise ValueError(
                f"Invalid data shape: number of snapshots n={n} must be greater than number of sensors m={m}."
            )

        if not (self.n_factors < m):
            raise ValueError(
                f"Invalid latent dimension: k={self.n_factors} must be strictly less than m={m}."
            )

        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0, ddof=1)

        self.std_ = np.where(self.std_ < 1e-15, 1e-15, self.std_)

        self.Z_ = (X - self.mean_) / self.std_

        self.R_ = np.cov(self.Z_, rowvar=False, ddof=1)

        fa = FactorAnalysis(
            n_components=self.n_factors,
            random_state=42
        )

        fa.fit(self.Z_)

        self.loadings_raw_ = fa.components_.T

        self.loadings_rotated_, self.rotation_matrix_ = varimax(self.loadings_raw_)

        self.communality_ = np.sum(self.loadings_rotated_**2, axis=1)
        self.communality_ = np.clip(self.communality_, 0, 1)

        self.uniqueness_ = 1 - self.communality_
        self.uniqueness_ = np.clip(self.uniqueness_, 0, 1)

        R_inv = np.linalg.pinv(self.R_)
        self.factor_scores_ = self.Z_ @ R_inv @ self.loadings_rotated_

        self.factor_score_variance_ = np.var(self.factor_scores_, axis=0, ddof=1)

        avg_communality = np.mean(self.communality_) * 100
        avg_uniqueness = np.mean(self.uniqueness_) * 100

        print("=== Factor Analysis Diagnostic Telemetry ===")
        print(f"Number of snapshots, n: {n}")
        print(f"Number of sensor channels, m: {m}")
        print(f"Number of latent factors, k: {self.n_factors}")
        print(f"Average System Communality %: {avg_communality:.4f}%")
        print(f"Average System Uniqueness %: {avg_uniqueness:.4f}%")

        summary_df = pd.DataFrame({
            "Sensor": self.numeric_columns_,
            "Communality_h2": self.communality_,
            "Uniqueness_phi2": self.uniqueness_
        })

        return summary_df

    def plot_diagnostics(self):
        factor_labels = [f"Factor_{i+1}" for i in range(self.n_factors)]
        sensor_labels = self.numeric_columns_

        fig = make_subplots(
            rows=2,
            cols=2,
            horizontal_spacing=0.24,
            vertical_spacing=0.28,
            subplot_titles=[
                "Structural Loadings Heatmap",
                "Variance Partitioning Profile",
                "Sensor Uniqueness Noise Floor",
                "Latent Factor Score Variance"
            ]
        )

        fig.add_trace(
            go.Heatmap(
                z=np.abs(self.loadings_rotated_),
                x=factor_labels,
                y=sensor_labels,
                colorscale="YlOrRd",
                colorbar=dict(
                    title="|Loading|",
                    x=-0.15,
                    len=0.38,
                    y=0.78,
                    yanchor="middle",
                    xanchor="right"
                ),
                name="|Rotated Loadings|"
            ),
            row=1,
            col=1
        )

        fig.add_trace(
            go.Bar(
                y=sensor_labels,
                x=self.communality_ * 100,
                orientation="h",
                name="Shared Communality h²",
                marker=dict(color="#1f77b4")
            ),
            row=1,
            col=2
        )

        fig.add_trace(
            go.Bar(
                y=sensor_labels,
                x=self.uniqueness_ * 100,
                orientation="h",
                name="Isolated Uniqueness φ²",
                marker=dict(color="#ff7f0e")
            ),
            row=1,
            col=2
        )

        fig.add_trace(
            go.Scatter(
                x=sensor_labels,
                y=self.uniqueness_,
                mode="lines+markers",
                name="Uniqueness φ²",
                line=dict(color="#d62728", width=2, dash="dashdot"),
                marker=dict(symbol="x", size=9)
            ),
            row=2,
            col=1
        )

        fig.add_trace(
            go.Bar(
                x=factor_labels,
                y=self.factor_score_variance_,
                name="Factor Score Variance",
                marker=dict(
                    color="#2ca02c",
                    line=dict(color="black", width=0.5)
                )
            ),
            row=2,
            col=2
        )

        fig.update_xaxes(title_text="Factor", row=1, col=1)
        fig.update_yaxes(title_text="Sensor", row=1, col=1)

        fig.update_xaxes(title_text="Variance Allocation (%)", range=[0, 100], row=1, col=2)
        fig.update_yaxes(title_text="Sensor", row=1, col=2)

        fig.update_xaxes(title_text="Sensor", tickangle=25, row=2, col=1)
        fig.update_yaxes(title_text="Uniqueness φ²", row=2, col=1)

        fig.update_xaxes(title_text="Latent Factor", row=2, col=2)
        fig.update_yaxes(title_text="Empirical Variance", row=2, col=2)

        fig.update_layout(
            title="2 × 2 Factor Diagnostics Grid Matrix",
            template="plotly_white",
            width=1250,
            height=750,
            barmode="stack",
            legend=dict(
                orientation="h",
                x=0.5,
                y=1.02,
                xanchor="center",
                yanchor="bottom"
            ),
            margin=dict(t=150, b=60, l=140, r=80)
        )

        fig.show()


fa_engine = FactorAnalysisDiagnosticEngine(n_factors=2)

fa_summary = fa_engine.fit(df_asset)

print("\n=== Sensor-Level FA Variance Partition Summary ===")
display(fa_summary)

fa_engine.plot_diagnostics()

   Sensor_1  Sensor_2  Sensor_3  Sensor_4
0  0.352140  1.086956  0.403534  0.753495
1 -0.156730  0.077262  0.778400 -1.379485
2 -0.021289  0.732151 -0.369800 -1.065461
3  1.134325  1.161528 -0.340645 -1.371333
4 -0.087697 -0.583662 -0.705439 -0.252842

=== Factor Analysis Diagnostic Telemetry ===
Number of snapshots, n: 2500
Number of sensor channels, m: 4
Number of latent factors, k: 2
Average System Communality %: 50.6586%
Average System Uniqueness %: 49.3414%

=== Sensor-Level FA Variance Partition Summary ===

     Sensor  Communality_h2  Uniqueness_phi2
0  Sensor_1        0.864586         0.135414
1  Sensor_2        0.875204         0.124796
2  Sensor_3        0.277897         0.722103
3  Sensor_4        0.008658         0.991342

### Numerical Interpretation

The Factor Analysis engine standardizes the sensor data using the unbiased sample standard deviation. A lower bound of \(10^{-15}\) is applied to the standard deviation to avoid division by zero if a sensor has no variation.

The fitted factor model separates each sensor into two parts:

$$
h_j^2
$$

and

$$
\varphi_j^2.
$$

The communality $h_j^2$ shows how much of the sensor variance is explained by the shared latent factors. The uniqueness $\varphi_j^2$ shows how much of the sensor variance remains isolated to that sensor.

The dashboard makes this separation clear. Sensors that are connected to the same physical process have strong factor loadings and high communality. A sensor with high uniqueness is more likely to contain local noise or instrumentation error.

In the generated data, Sensor 4 was given a large isolated noise term. Therefore, it should appear with a high uniqueness value. This means its behaviour is not mainly explained by the shared structural factors. In a real monitoring system, this would suggest a possible sensor fault or local measurement problem rather than a global structural mode.

# Subspace Diagnostics & Feature De-correlation

This section compares PCA and FA using the same 4-channel sensor system. PCA is treated as a geometric method that captures total variance. FA is treated as a generative method that separates shared structural behaviour from sensor-specific noise.

The main aim is to see how each method behaves when one sensor contains a large local instrumentation fault.

## Part A: Develop a Feature Analysis Dashboard

Two dashboards are developed in this section.

The first dashboard is the PCA Optimization Suite. It shows the PCA loading matrix, eigenvalues, marginal and cumulative explained variance, residual unexplained variance, mean $T^2$, and mean $Q$.

The second dashboard is the FA Latent Subspace Suite. It shows the rotated factor loadings, communality-uniqueness partition, sensor uniqueness profile, and empirical factor score variance.

Both dashboards use the same synthetic sensor dataset so that the behaviour of PCA and FA can be compared directly.

In [32]:
# ============================================================
# Subspace Diagnostics & Feature De-correlation
# Part A: PCA + FA Feature Analysis Dashboards
# ============================================================

import numpy as np
import pandas as pd

from sklearn.decomposition import FactorAnalysis
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from IPython.display import Markdown, display


# ------------------------------------------------------------
# Synthetic multi-sensor asset data
# ------------------------------------------------------------

np.random.seed(42)

n_samples = 2500

f1 = np.random.normal(0, 1, n_samples)
f2 = np.random.normal(0, 1, n_samples)

s1 = 0.85 * f1 + 0.10 * f2 + np.random.normal(0, 0.30, n_samples)
s2 = 0.80 * f1 + 0.15 * f2 + np.random.normal(0, 0.35, n_samples)
s3 = 0.12 * f1 + 0.90 * f2 + np.random.normal(0, 0.25, n_samples)
s4 = 0.02 * f1 + 0.05 * f2 + np.random.normal(0, 1.40, n_samples)

df_asset = pd.DataFrame(
    data=np.vstack([s1, s2, s3, s4]).T,
    columns=["Sensor_1", "Sensor_2", "Sensor_3", "Sensor_4"]
)

display(df_asset.head())


# ------------------------------------------------------------
# Varimax rotation helper
# ------------------------------------------------------------

def varimax(Phi, gamma=1.0, q=50, tol=1e-6):
    """
    Performs orthogonal Varimax rotation.
    Phi shape: m x k
    """

    p, k = Phi.shape
    R = np.eye(k)
    d_old = 0

    for _ in range(q):
        Lambda = Phi @ R

        u, s, vh = np.linalg.svd(
            Phi.T @ (
                Lambda**3
                - (gamma / p) * Lambda @ np.diag(np.diag(Lambda.T @ Lambda))
            )
        )

        R = u @ vh
        d_new = np.sum(s)

        if d_old != 0 and d_new / d_old < 1 + tol:
            break

        d_old = d_new

    return Phi @ R, R


# ------------------------------------------------------------
# PCA dashboard
# ------------------------------------------------------------

def build_pca_dashboard(df: pd.DataFrame):
    numeric_df = df.select_dtypes(include=[np.number]).copy()
    sensor_labels = numeric_df.columns.tolist()

    X = numeric_df.to_numpy(dtype=float)

    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0, ddof=1)
    std = np.where(std < 1e-15, 1e-15, std)

    Z = (X - mean) / std

    S = np.cov(Z, rowvar=False, ddof=1)

    eigenvalues, eigenvectors = np.linalg.eigh(S)

    sort_idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sort_idx]
    eigenvectors = eigenvectors[:, sort_idx]

    scores = Z @ eigenvectors

    total_variance = np.sum(eigenvalues)

    marginal_explained = eigenvalues / total_variance * 100
    cumulative_explained = np.cumsum(marginal_explained)
    residual_unexplained = 100 - cumulative_explained

    component_labels = [f"PC{i+1}" for i in range(len(eigenvalues))]

    k_values = [1, 2, 3]
    mean_T2 = []
    mean_Q = []

    for k in k_values:
        T2_values = np.sum((scores[:, :k] ** 2) / eigenvalues[:k], axis=1)
        Q_values = np.sum(scores[:, k:] ** 2, axis=1)

        mean_T2.append(np.mean(T2_values))
        mean_Q.append(np.mean(Q_values))

    pca_summary = pd.DataFrame({
        "Component": component_labels,
        "Eigenvalue": eigenvalues,
        "Marginal_Explained_%": marginal_explained,
        "Cumulative_Explained_%": cumulative_explained,
        "Residual_Unexplained_%": residual_unexplained
    })

    pca_metrics = pd.DataFrame({
        "k": k_values,
        "Mean_T2": mean_T2,
        "Mean_Q": mean_Q
    })

    print("=== PCA Eigenvalue and Variance Summary ===")
    display(pca_summary)

    print("\n=== PCA T² and Q Summary ===")
    display(pca_metrics)

    fig = make_subplots(
        rows=2,
        cols=3,
        horizontal_spacing=0.12,
        vertical_spacing=0.25,
        subplot_titles=[
            "Feature Loadings Matrix |P(j,r)|",
            "Absolute Eigenvalues",
            "Explained Variance Profile",
            "Residual Unexplained Variance",
            "Mean Hotelling's T² vs k",
            "Mean Q Statistic vs k"
        ],
        specs=[
            [{"type": "heatmap"}, {"type": "bar"}, {"type": "xy"}],
            [{"type": "bar"}, {"type": "xy"}, {"type": "xy"}]
        ]
    )

    fig.add_trace(
        go.Heatmap(
            z=np.abs(eigenvectors),
            x=component_labels,
            y=sensor_labels,
            colorscale="YlGnBu",
            colorbar=dict(title="|Loading|"),
            name="|P(j,r)|"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Bar(
            x=component_labels,
            y=eigenvalues,
            name="Eigenvalues",
            marker=dict(color="#1f77b4")
        ),
        row=1,
        col=2
    )

    fig.add_trace(
        go.Bar(
            x=component_labels,
            y=marginal_explained,
            name="Marginal Explained %",
            marker=dict(color="#ff7f0e")
        ),
        row=1,
        col=3
    )

    fig.add_trace(
        go.Scatter(
            x=component_labels,
            y=cumulative_explained,
            mode="lines+markers",
            name="Cumulative Explained %",
            line=dict(color="#2ca02c", dash="dash")
        ),
        row=1,
        col=3
    )

    fig.add_trace(
        go.Bar(
            x=component_labels,
            y=residual_unexplained,
            name="Residual Unexplained %",
            marker=dict(color="#d62728")
        ),
        row=2,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=k_values,
            y=mean_T2,
            mode="lines+markers",
            name="Mean T²",
            line=dict(color="#9467bd")
        ),
        row=2,
        col=2
    )

    fig.add_trace(
        go.Scatter(
            x=k_values,
            y=mean_Q,
            mode="lines+markers",
            name="Mean Q",
            line=dict(color="#8c564b")
        ),
        row=2,
        col=3
    )

    fig.update_xaxes(title_text="Principal Component", row=1, col=1)
    fig.update_yaxes(title_text="Sensor", row=1, col=1)

    fig.update_xaxes(title_text="Principal Component", row=1, col=2)
    fig.update_yaxes(title_text="Eigenvalue", row=1, col=2)

    fig.update_xaxes(title_text="Principal Component", row=1, col=3)
    fig.update_yaxes(title_text="Variance %", row=1, col=3)

    fig.update_xaxes(title_text="Principal Component", row=2, col=1)
    fig.update_yaxes(title_text="Residual Variance %", row=2, col=1)

    fig.update_xaxes(title_text="Subspace Size k", row=2, col=2)
    fig.update_yaxes(title_text="Mean T²", row=2, col=2)

    fig.update_xaxes(title_text="Subspace Size k", row=2, col=3)
    fig.update_yaxes(title_text="Mean Q", row=2, col=3)

    fig.update_layout(
        title="PCA Optimization Suite: 2 × 3 Diagnostic Dashboard",
        template="plotly_white",
        width=1500,
        height=850,
        legend=dict(
            orientation="h",
            x=0.5,
            y=1.08,
            xanchor="center"
        ),
        margin=dict(t=150, b=70, l=90, r=80)
    )

    fig.show()

    return pca_summary, pca_metrics


# ------------------------------------------------------------
# FA dashboard
# ------------------------------------------------------------

def build_fa_dashboard(df: pd.DataFrame, n_factors: int = 2):
    numeric_df = df.select_dtypes(include=[np.number]).copy()
    sensor_labels = numeric_df.columns.tolist()

    X = numeric_df.to_numpy(dtype=float)

    n, m = X.shape

    if n <= m:
        raise ValueError("The number of snapshots n must be greater than the number of sensors m.")

    if not (n_factors < m):
        raise ValueError("The number of latent factors k must be strictly less than m.")

    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0, ddof=1)
    std = np.where(std < 1e-15, 1e-15, std)

    Z = (X - mean) / std

    R = np.cov(Z, rowvar=False, ddof=1)

    fa = FactorAnalysis(
        n_components=n_factors,
        random_state=42
    )

    fa.fit(Z)

    loadings_raw = fa.components_.T
    loadings_rotated, rotation_matrix = varimax(loadings_raw)

    communality = np.sum(loadings_rotated**2, axis=1)
    communality = np.clip(communality, 0, 1)

    uniqueness = 1 - communality
    uniqueness = np.clip(uniqueness, 0, 1)

    factor_scores = Z @ np.linalg.pinv(R) @ loadings_rotated
    factor_score_variance = np.var(factor_scores, axis=0, ddof=1)

    factor_labels = [f"Factor_{i+1}" for i in range(n_factors)]

    fa_summary_dashboard = pd.DataFrame({
        "Sensor": sensor_labels,
        "Communality_h2": communality,
        "Uniqueness_phi2": uniqueness,
        "Communality_%": communality * 100,
        "Uniqueness_%": uniqueness * 100
    })

    factor_variance_summary = pd.DataFrame({
        "Factor": factor_labels,
        "Empirical_Factor_Score_Variance": factor_score_variance
    })

    print("=== FA Sensor-Level Variance Partition Summary ===")
    display(fa_summary_dashboard)

    print("\n=== FA Latent Factor Score Variance Summary ===")
    display(factor_variance_summary)

    max_unique_sensor = fa_summary_dashboard.loc[
        fa_summary_dashboard["Uniqueness_phi2"].idxmax(),
        "Sensor"
    ]

    print(f"\nHighest uniqueness is observed in: {max_unique_sensor}")

    fig = make_subplots(
        rows=2,
        cols=2,
        horizontal_spacing=0.24,
        vertical_spacing=0.28,
        subplot_titles=[
            "Structural Loadings Matrix",
            "Variance Allocation: Communality vs Uniqueness",
            "Sensor Uniqueness Noise Floor",
            "Latent Factor Score Variance"
        ]
    )

    fig.add_trace(
        go.Heatmap(
            z=np.abs(loadings_rotated),
            x=factor_labels,
            y=sensor_labels,
            colorscale="YlOrRd",
            colorbar=dict(
                title="|Loading|",
                x=-0.15,
                len=0.38,
                y=0.78,
                yanchor="middle",
                xanchor="right"
            ),
            name="|Rotated Loadings|"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Bar(
            y=sensor_labels,
            x=communality * 100,
            orientation="h",
            name="Shared Communality h²",
            marker=dict(color="#1f77b4")
        ),
        row=1,
        col=2
    )

    fig.add_trace(
        go.Bar(
            y=sensor_labels,
            x=uniqueness * 100,
            orientation="h",
            name="Channel Uniqueness φ²",
            marker=dict(color="#ff7f0e")
        ),
        row=1,
        col=2
    )

    fig.add_trace(
        go.Scatter(
            x=sensor_labels,
            y=uniqueness,
            mode="lines+markers",
            name="Uniqueness φ²",
            line=dict(color="#d62728", width=2, dash="dashdot"),
            marker=dict(symbol="x", size=9)
        ),
        row=2,
        col=1
    )

    fig.add_trace(
        go.Bar(
            x=factor_labels,
            y=factor_score_variance,
            name="Factor Score Variance",
            marker=dict(
                color="#2ca02c",
                line=dict(color="black", width=0.5)
            )
        ),
        row=2,
        col=2
    )

    fig.update_xaxes(title_text="Latent Factor", row=1, col=1)
    fig.update_yaxes(title_text="Sensor", row=1, col=1)

    fig.update_xaxes(title_text="Variance Allocation (%)", range=[0, 100], row=1, col=2)
    fig.update_yaxes(title_text="Sensor", row=1, col=2)

    fig.update_xaxes(title_text="Sensor", tickangle=25, row=2, col=1)
    fig.update_yaxes(title_text="Uniqueness φ²", row=2, col=1)

    fig.update_xaxes(title_text="Latent Factor", row=2, col=2)
    fig.update_yaxes(title_text="Empirical Variance", row=2, col=2)

    fig.update_layout(
        title="FA Latent Subspace Suite: 2 × 2 Diagnostic Dashboard",
        template="plotly_white",
        width=1250,
        height=750,
        barmode="stack",
        legend=dict(
            orientation="h",
            x=0.5,
            y=1.02,
            xanchor="center",
            yanchor="bottom"
        ),
        margin=dict(t=150, b=60, l=140, r=80)
    )

    fig.show()

    return fa_summary_dashboard, factor_variance_summary


# ------------------------------------------------------------
# Execute dashboards
# ------------------------------------------------------------

pca_summary, pca_metrics = build_pca_dashboard(df_asset)

fa_summary_dashboard, fa_factor_variance = build_fa_dashboard(df_asset, n_factors=2)

   Sensor_1  Sensor_2  Sensor_3  Sensor_4
0  0.352140  1.086956  0.403534  0.753495
1 -0.156730  0.077262  0.778400 -1.379485
2 -0.021289  0.732151 -0.369800 -1.065461
3  1.134325  1.161528 -0.340645 -1.371333
4 -0.087697 -0.583662 -0.705439 -0.252842

=== PCA Eigenvalue and Variance Summary ===

,Component,Eigenvalue,Marginal_Explained_%,Cumulative_Explained_%,Residual_Unexplained_%
0,PC1,1.974420,49.360512,49.360512,5.063949e+01
1,PC2,1.006968,25.174209,74.534721,2.546528e+01
2,PC3,0.881088,22.027198,96.561920,3.438080e+00
3,PC4,0.137523,3.438080,100.000000,1.421085e-14

=== PCA T² and Q Summary ===

   k  Mean_T2    Mean_Q
0  1   0.9996  2.024769
1  2   1.9992  1.018204
2  3   2.9988  0.137468

=== FA Sensor-Level Variance Partition Summary ===

     Sensor  Communality_h2  Uniqueness_phi2  Communality_%  Uniqueness_%
0  Sensor_1        0.864586         0.135414      86.458615     13.541385
1  Sensor_2        0.875204         0.124796      87.520379     12.479621
2  Sensor_3        0.277897         0.722103      27.789716     72.210284
3  Sensor_4        0.008658         0.991342       0.865849     99.134151

=== FA Latent Factor Score Variance Summary ===

     Factor  Empirical_Factor_Score_Variance
0  Factor_1                         0.925003
1  Factor_2                         0.284073

Highest uniqueness is observed in: Sensor_4

### Dashboard Interpretation

The PCA dashboard shows how the total system variance is distributed across principal components. It is useful for seeing how much variance is captured by each component and how the \(T^2\) and \(Q\) statistics change with the subspace size.

The FA dashboard gives a different type of information. It separates each sensor into shared communality and isolated uniqueness. This is more useful when the goal is not only to reduce dimension, but also to diagnose whether a sensor is part of the common structural behaviour or mainly producing its own local noise.

Since Sensor 4 was generated with a large isolated noise term, it is expected to show high uniqueness in the FA dashboard.

## Part B: Analysis

The following answers use the numerical results from the PCA and FA dashboards. Each question has its own code cell to show the relevant evidence, followed by a short written interpretation.

In [33]:
# ============================================================
# Question 1 Code: The Total Variance Illusion
# ============================================================

raw_variances = df_asset.var(ddof=1)
correlation_matrix = df_asset.corr()

highest_variance_sensor = raw_variances.idxmax()
highest_variance_value = raw_variances.max()

highest_uniqueness_sensor = fa_summary_dashboard.loc[
    fa_summary_dashboard["Uniqueness_phi2"].idxmax(),
    "Sensor"
]

highest_uniqueness_value = fa_summary_dashboard["Uniqueness_phi2"].max()

pc1_percent = pca_summary.loc[0, "Marginal_Explained_%"]
pc2_percent = pca_summary.loc[1, "Marginal_Explained_%"]
pc1_pc2_total = pca_summary.loc[1, "Cumulative_Explained_%"]

print("=== Question 1: Numerical Evidence ===")
print(f"Highest raw variance sensor: {highest_variance_sensor}")
print(f"Highest raw variance value: {highest_variance_value:.4f}")
print(f"PC1 explained variance: {pc1_percent:.2f}%")
print(f"PC2 explained variance: {pc2_percent:.2f}%")
print(f"PC1 + PC2 cumulative explained variance: {pc1_pc2_total:.2f}%")
print(f"Highest uniqueness sensor: {highest_uniqueness_sensor}")
print(f"Highest uniqueness value: {highest_uniqueness_value * 100:.2f}%")

print("\n=== Raw Sensor Variances ===")
display(raw_variances.to_frame(name="Variance"))

print("\n=== Sensor Correlation Matrix ===")
display(correlation_matrix)

print("\n=== FA Communality and Uniqueness Table ===")
display(fa_summary_dashboard)

=== Question 1: Numerical Evidence ===
Highest raw variance sensor: Sensor_4
Highest raw variance value: 2.0173
PC1 explained variance: 49.36%
PC2 explained variance: 25.17%
PC1 + PC2 cumulative explained variance: 74.53%
Highest uniqueness sensor: Sensor_4
Highest uniqueness value: 99.13%

=== Raw Sensor Variances ===

          Variance
Sensor_1  0.794446
Sensor_2  0.763960
Sensor_3  0.891709
Sensor_4  2.017258

=== Sensor Correlation Matrix ===

          Sensor_1  Sensor_2  Sensor_3  Sensor_4
Sensor_1  1.000000  0.859319  0.195527  0.035481
Sensor_2  0.859319  1.000000  0.266624  0.039543
Sensor_3  0.195527  0.266624  1.000000  0.056603
Sensor_4  0.035481  0.039543  0.056603  1.000000

=== FA Communality and Uniqueness Table ===

     Sensor  Communality_h2  Uniqueness_phi2  Communality_%  Uniqueness_%
0  Sensor_1        0.864586         0.135414      86.458615     13.541385
1  Sensor_2        0.875204         0.124796      87.520379     12.479621
2  Sensor_3        0.277897         0.722103      27.789716     72.210284
3  Sensor_4        0.008658         0.991342       0.865849     99.134151

### Question 1: The Total Variance Illusion

A uniqueness value close to 100% means that most of the variation in that sensor is not explained by the shared physical latent factors of the system. In this dataset, Sensor 4 has the highest uniqueness value. This shows that the signal from Sensor 4 is mostly sensor-specific noise rather than useful shared structural behaviour.

This also agrees with the way the dataset was generated. Sensor 4 was given a large local noise term, so it behaves like a faulty or poorly calibrated sensor.

PCA can be misled here because it focuses on total variance. It does not know whether the variance is coming from a real structural mode or from a noisy sensor. Since Sensor 4 has a large raw variance, PCA can give importance to directions influenced by that sensor. This can inflate the top eigenvalues.

This would be risky in plant monitoring. A noisy sensor could be treated as an important structural pattern, which may lead to false alarms or incorrect thresholds. The monitoring system might react to instrumentation noise instead of actual structural behaviour.

Therefore, the total variance illusion is that PCA may treat large variance as important even when it is mostly local sensor noise. FA gives a clearer diagnosis because it separates shared communality from sensor-specific uniqueness.

In [34]:
# ============================================================
# Question 2 Code: Decoupling Structural Loading via Rotation
# ============================================================

X = df_asset.select_dtypes(include=[np.number]).to_numpy(dtype=float)
sensor_labels = df_asset.select_dtypes(include=[np.number]).columns.tolist()

mean = np.mean(X, axis=0)
std = np.std(X, axis=0, ddof=1)
std = np.where(std < 1e-15, 1e-15, std)

Z = (X - mean) / std

S = np.cov(Z, rowvar=False, ddof=1)
eigenvalues, eigenvectors = np.linalg.eigh(S)

sort_idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sort_idx]
eigenvectors = eigenvectors[:, sort_idx]

pca_loading_table = pd.DataFrame(
    np.abs(eigenvectors),
    index=sensor_labels,
    columns=[f"PC_{i+1}" for i in range(eigenvectors.shape[1])]
)

fa_temp = FactorAnalysis(n_components=2, random_state=42)
fa_temp.fit(Z)

loadings_raw = fa_temp.components_.T
loadings_rotated, rotation_matrix = varimax(loadings_raw)

fa_loading_table = pd.DataFrame(
    np.abs(loadings_rotated),
    index=sensor_labels,
    columns=["Factor_1", "Factor_2"]
)

dominant_factor = fa_loading_table.idxmax(axis=1).to_frame(name="Dominant_Factor")

print("=== Question 2: PCA Absolute Eigenvector Loadings ===")
display(pca_loading_table)

print("\n=== Question 2: FA Absolute Rotated Loadings ===")
display(fa_loading_table)

print("\n=== Dominant FA Factor for Each Sensor ===")
display(dominant_factor)

=== Question 2: PCA Absolute Eigenvector Loadings ===

              PC_1      PC_2      PC_3      PC_4
Sensor_1  0.661457  0.127519  0.245049  0.697255
Sensor_2  0.674067  0.101113  0.159700  0.714077
Sensor_3  0.321240  0.267494  0.906269  0.062681
Sensor_4  0.070100  0.949717  0.305162  0.000059

=== Question 2: FA Absolute Rotated Loadings ===

          Factor_1  Factor_2
Sensor_1  0.929823  0.003950
Sensor_2  0.924437  0.143596
Sensor_3  0.212814  0.482294
Sensor_4  0.033911  0.086652

=== Dominant FA Factor for Each Sensor ===

         Dominant_Factor
Sensor_1        Factor_1
Sensor_2        Factor_1
Sensor_3        Factor_2
Sensor_4        Factor_2

### Question 2: Decoupling Structural Loading via Rotation

Traditional PCA gives components according to a strict variance order,

$$
\lambda_1 > \lambda_2 > \cdots.
$$

Each principal component is chosen to capture as much remaining variance as possible. This makes PCA very useful for compression, but the components can be harder to interpret because one component may mix several sensor effects.

Varimax rotation in Factor Analysis has a different goal. It keeps the factors orthogonal, but rotates the loading structure to make it easier to read. The aim is for each sensor to load strongly on one factor and weakly on the others.

In the FA loading table, Sensor 1 and Sensor 2 mainly load on Factor 1, while Sensor 3 mainly loads on Factor 2. This matches the synthetic data because Sensor 1 and Sensor 2 were built from the primary structural process, while Sensor 3 was built mainly from the secondary process.

This rotated FA view is useful for a plant operator. If Factor 1 becomes abnormal, attention can go to the Sensor 1 and Sensor 2 group. If Factor 2 becomes abnormal, Sensor 3 becomes the main channel to inspect.

A raw PCA eigenvector matrix is less direct because the principal components may mix several sensors. Therefore, PCA is better for capturing total variance, while rotated FA is better for troubleshooting and explaining which sensor group is linked to which hidden process.

In [35]:
# ============================================================
# Question 3 Code: Determining Subspace Truncation k using T² and Q
# ============================================================

q_k1 = pca_metrics.loc[pca_metrics["k"] == 1, "Mean_Q"].iloc[0]
q_k2 = pca_metrics.loc[pca_metrics["k"] == 2, "Mean_Q"].iloc[0]
q_k3 = pca_metrics.loc[pca_metrics["k"] == 3, "Mean_Q"].iloc[0]

t2_k1 = pca_metrics.loc[pca_metrics["k"] == 1, "Mean_T2"].iloc[0]
t2_k2 = pca_metrics.loc[pca_metrics["k"] == 2, "Mean_T2"].iloc[0]
t2_k3 = pca_metrics.loc[pca_metrics["k"] == 3, "Mean_T2"].iloc[0]

q_drop_1_to_2 = q_k1 - q_k2
q_drop_2_to_3 = q_k2 - q_k3

print("=== Question 3: T² and Q Metrics ===")
display(pca_metrics)

print("\n=== Q Statistic Drop Analysis ===")
print(f"Mean Q at k = 1: {q_k1:.4f}")
print(f"Mean Q at k = 2: {q_k2:.4f}")
print(f"Mean Q at k = 3: {q_k3:.4f}")

print(f"\nDrop in Q from k = 1 to k = 2: {q_drop_1_to_2:.4f}")
print(f"Drop in Q from k = 2 to k = 3: {q_drop_2_to_3:.4f}")

print("\n=== T² Statistic Growth ===")
print(f"Mean T² at k = 1: {t2_k1:.4f}")
print(f"Mean T² at k = 2: {t2_k2:.4f}")
print(f"Mean T² at k = 3: {t2_k3:.4f}")

if q_drop_1_to_2 > q_drop_2_to_3:
    print("\nConclusion: The elbow occurs around k = 2.")
else:
    print("\nConclusion: The Q profile does not show a clear elbow at k = 2.")

=== Question 3: T² and Q Metrics ===

   k  Mean_T2    Mean_Q
0  1   0.9996  2.024769
1  2   1.9992  1.018204
2  3   2.9988  0.137468

=== Q Statistic Drop Analysis ===
Mean Q at k = 1: 2.0248
Mean Q at k = 2: 1.0182
Mean Q at k = 3: 0.1375

Drop in Q from k = 1 to k = 2: 1.0066
Drop in Q from k = 2 to k = 3: 0.8807

=== T² Statistic Growth ===
Mean T² at k = 1: 0.9996
Mean T² at k = 2: 1.9992
Mean T² at k = 3: 2.9988

Conclusion: The elbow occurs around k = 2.

### Question 3: Determining Subspace Truncation \(k\) using \(T^2\) and \(Q\) Profiles

The mean \(Q\) statistic shows how much residual energy is left outside the retained PCA subspace. When \(k\) increases, more principal components are retained, so the \(Q\) value should reduce.

The results show a clear drop in mean \(Q\) when the cutoff changes from \(k=1\) to \(k=2\). This means that the second component captures an important part of the system behaviour that was not captured by the first component alone.

When the cutoff changes from \(k=2\) to \(k=3\), the reduction in \(Q\) is smaller. This gives an elbow around \(k=2\). That suggests that the first two components contain the main physical information in the data.

Therefore, \(k=2\) is the best truncation choice. This also agrees with the construction of the dataset, since the sensor data was generated from two hidden physical driving forces, \(f_1\) and \(f_2\).

If \(k=3\) is selected, part of the residual behaviour may be absorbed into the normal PCA model. In this dataset, that extra component can include local noise from Sensor 4. This is risky because sensor noise that should stay in the residual \(Q\) space may be treated as normal system behaviour.

In [36]:
# ============================================================
# Question 4 Code: Operational Trade-offs in System Health Monitoring
# ============================================================

fa_tradeoff_table = fa_summary_dashboard.copy()

most_noise_dominated_sensor = fa_tradeoff_table.loc[
    fa_tradeoff_table["Uniqueness_phi2"].idxmax(),
    "Sensor"
]

most_noise_uniqueness = fa_tradeoff_table["Uniqueness_phi2"].max()

most_shared_sensor = fa_tradeoff_table.loc[
    fa_tradeoff_table["Communality_h2"].idxmax(),
    "Sensor"
]

most_shared_communality = fa_tradeoff_table["Communality_h2"].max()

print("=== Question 4: FA Noise Floor Metrics ===")
display(fa_tradeoff_table)

print("\n=== Diagnostic Summary ===")
print(f"Most noise-dominated sensor: {most_noise_dominated_sensor}")
print(f"Uniqueness of most noise-dominated sensor: {most_noise_uniqueness * 100:.2f}%")

print(f"\nMost shared-structure sensor: {most_shared_sensor}")
print(f"Communality of most shared-structure sensor: {most_shared_communality * 100:.2f}%")

print("\nRecommended robustness strategy:")
print("FA is more robust for a single sensor calibration loss or electrical short,")
print("because uniqueness directly measures isolated sensor-specific noise.")

=== Question 4: FA Noise Floor Metrics ===

     Sensor  Communality_h2  Uniqueness_phi2  Communality_%  Uniqueness_%
0  Sensor_1        0.864586         0.135414      86.458615     13.541385
1  Sensor_2        0.875204         0.124796      87.520379     12.479621
2  Sensor_3        0.277897         0.722103      27.789716     72.210284
3  Sensor_4        0.008658         0.991342       0.865849     99.134151

=== Diagnostic Summary ===
Most noise-dominated sensor: Sensor_4
Uniqueness of most noise-dominated sensor: 99.13%

Most shared-structure sensor: Sensor_2
Communality of most shared-structure sensor: 87.52%

Recommended robustness strategy:
FA is more robust for a single sensor calibration loss or electrical short,
because uniqueness directly measures isolated sensor-specific noise.

### Question 4: Operational Trade-offs in System Health Monitoring

The PCA strategy uses Hotelling's \(T^2\) statistic to monitor movement inside the retained principal component subspace. It uses the \(Q\) statistic to monitor residual behaviour outside that subspace. This is useful for broad anomaly detection because it separates modelled variation from unexplained residual variation.

The FA strategy monitors rotated latent factor scores and also separates each sensor into communality and uniqueness. This is useful when the aim is not only to detect an anomaly, but also to understand whether the anomaly belongs to the shared structural behaviour or to a single sensor.

For a single sensor losing calibration or experiencing an electrical short, FA is more robust. The reason is that FA directly calculates the uniqueness value,

$$
\varphi_j^2.
$$

This value measures the part of the sensor variance that is not explained by the shared latent structure.

In the results, Sensor 4 has the largest uniqueness value. This means that its behaviour is mostly local sensor-specific noise, not shared structural behaviour. So FA can clearly identify Sensor 4 as the likely problematic channel.

PCA may still detect the issue through the \(Q\) statistic, but PCA itself does not directly explain whether the abnormal variance is caused by a sensor fault or a real structural mode. Since PCA is driven by total variance, a large sensor fault can distort the eigenvalues and components.

Therefore, FA is more robust for detecting a single sensor calibration fault or electrical short. In practice, a good monitoring system could use PCA \(T^2\) and \(Q\) for general anomaly detection, and then use FA uniqueness values to decide whether the anomaly is likely structural or sensor-specific.